# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_ip',
            field=models.GenericIPAddressField(default=network.models.Device.IPAddress, protocol='IPv4', unique=True),
        ),
    ]
