# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('publish_device', 'Can use this device on the network'),)},
        ),
    ]
