# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 09:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='IP address')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, verbose_name='Label')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
                ('default_state', models.CharField(choices=[('AUTO', 'Auto'), ('AUTHORIZED', 'Authorized'), ('UNAUTHORIZED', 'Unauthorized')], default='AUTO', max_length=12, verbose_name='Default state')),
                ('current_state', models.CharField(choices=[('AUTO', 'Auto'), ('AUTHORIZED', 'Authorized'), ('UNAUTHORIZED', 'Unauthorized')], default='AUTO', max_length=12, verbose_name='Current state')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethernet_auth.Switch')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchPortAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_state', models.CharField(choices=[('AUTO', 'Auto'), ('AUTHORIZED', 'Authorized'), ('UNAUTHORIZED', 'Unauthorized')], max_length=12, verbose_name='New state')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration date')),
                ('switch_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ethernet_auth.SwitchPort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
