# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=25, verbose_name='First name')),
                ('lastName', models.CharField(max_length=25, verbose_name='Last name')),
                ('email', models.EmailField(max_length=50, verbose_name='E-Mail')),
                ('validationToken', models.CharField(max_length=256, verbose_name='Validation token')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
        ),
    ]
