# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='pendinguser',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='pendinguser',
            old_name='validationToken',
            new_name='validation_token',
        ),
    ]
