# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160719_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='E-Mail'),
        ),
    ]
