# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cleaning',
            field=models.BooleanField(default=True),
        ),
    ]
